train_splits: 64
params:
  cifar10:
    name: &dataset_name 'cifar10'
    type: 'CIFAR10'
    #    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    root: &root_dir './resources/dataset/cifar10'
    splits:
      train:
        #        dataset_id: &cifar10_train !join [*dataset_name, '/train']
        dataset_id: &cifar10_train 'cifar10/train'
        params:
          root: *root_dir
          train: True
          download: True
          transform_params:
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [ 0.49139968, 0.48215841, 0.44653091 ]
                std: [ 0.24703223, 0.24348513, 0.26158784 ]
#            - &resize
#              type: 'WrappedResize'
#              params:
#                size: &input_size [224, 224]
#                interpolation: 'bicubic'
#                antialias: True
      val:
        #        dataset_id: &cifar10_val !join [*dataset_name, '/val']
        dataset_id: &cifar10_val 'cifar10/val'
        params:
          root: *root_dir
          train: False
          download: True
          transform_params: &val_transform
            - type: 'ToTensor'
              params:
            - *normalize
#            - *resize
      test:
        #        dataset_id: &cifar10_test !join [*dataset_name, '/test']
        dataset_id: &cifar10_test 'cifar10/test'
        params:
          root: *root_dir
          train: False
          download: True
          transform_params: *val_transform
